### ISSUE TITLE
Python3.x源码中找不到Includes/intobject.h

### ISSUE THREAD

**Issue by kernellmd** [shishujuan/python-source-code-analysis#2]
老哥，我再GitHub上Python官方发布的源码中并没有找到intobject和intobject.c文件，请问老哥找到过吗，怎么找的？

**Comment by shishujuan** [comment]
@kernellmd python3.x版本代码没有看过噢，这本书是以python2.x版本分析的哈。

**Comment by kernellmd** [comment]
哦哦，好的吧，麻烦老哥了。
